<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="ManageMessages.aspx.vb" Inherits="SchloetterSalesPortal.ManageMessages" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<h2>Manage Messages</h2>
<asp:ValidationSummary ID="HeaderValidationSummary" runat="server" ValidationGroup="HeaderValidation" />
<div class="MainContent">
    <div class="FormHeader"> 
        <div class="twocolleft50"> 
            <div class="Table">
                    <div class="Row">
                        <div class="Cell"><asp:Label ID="lblForMessageTitle" runat="server" Text="Title" ></asp:Label></div>
                        <div class="Cell"><asp:TextBox ID="MessageTitle" runat="server" MaxLength="15" CssClass="textEntry" ></asp:TextBox>
                                          <asp:RequiredFieldValidator ID="MessageTitleRequiredFieldValidator" runat="server" ErrorMessage="Message Title required" ControlToValidate="MessageTitle" ValidationGroup="HeaderValidation">*</asp:RequiredFieldValidator>
                            </div>
                    </div>
                    <div class="Row">
                        <div class="Cell"><asp:Label ID="lblForMessage" runat="server" Text="Message" ></asp:Label></div>
                        <div class="Cell"><asp:TextBox ID="Message" runat="server" MaxLength="200" CssClass="textEntry" Columns="40" TextMode="MultiLine" Rows="5" ></asp:TextBox>
                                          <asp:RequiredFieldValidator ID="MessageRequiredFieldValidator" runat="server" ErrorMessage="Message required" ControlToValidate="Message" ValidationGroup="HeaderValidation">*</asp:RequiredFieldValidator>  
                        </div>
                    </div>
                    <div class="Row">
                        <div class="Cell"><asp:Label ID="lblForActive" runat="server" Text="Active" ></asp:Label></div>
                        <div class="Cell"><asp:CheckBox runat="server" ID="Active" /></div>
                    </div>
                    <div class="Row">
                        <div class="Cell"></div>
                        <div class="Cell"><asp:Button ID="btnNew" runat="server"  Text="New" CssClass="Action-Button" /><asp:Button ID="btnAddOrUpdate" runat="server"  Text="Save" CssClass="Action-Button" ValidationGroup="HeaderValidation" /></div>
                    </div>  
            </div>
        </div>
        <div class="twocolright50">
             <center>
             <asp:GridView ID="MessagesListGrid"
             AllowSorting="false"
             AllowPaging="True" 
             runat="server"
             CellPadding="4"
             ForeColor="#333333"
             AutoGenerateColumns="False" AutoGenerateDeleteButton="False" AutoGenerateSelectButton="False"
             ShowHeaderWhenEmpty="True"
             GridLines="None"
             EmptyDataText="No Record found"
             CssClass="ItemGrid"     
             PageSize="8"              
             DataKeyNames="Idkey"
             >
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" HorizontalAlign="Left" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                <Columns>                                      
                    <asp:BoundField DataField="IdKey" HeaderText="#" ReadOnly="True"  />   
                    <asp:BoundField DataField="MessageTitle" HeaderText="Title" ReadOnly="True"  />      
                    <asp:BoundField DataField="Message" HeaderText="Message" ReadOnly="True"  />   
                    <asp:BoundField DataField="Active" HeaderText="Active" ReadOnly="True"  />                                                                                                      
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="btnDelete" runat="server" CommandArgument='<%# Container.DataItemIndex %>'  OnClientClick = "return confirm('Do you want to delete?')"  CommandName="DeleteItem" Text="Delete" />
                            <asp:LinkButton ID="btnSelect" runat="server" CommandArgument='<%# Container.DataItemIndex %>'  CommandName="Select" Text="Select" />
                        </ItemTemplate>
                    </asp:TemplateField>                
                </Columns>
                </asp:GridView>
                 <% If MessagesListGrid.Rows(0).Cells.Count > 1 Then%>
                <i>You are viewing page
                <%=MessagesListGrid.PageIndex + 1%>
                of
                <%=MessagesListGrid.PageCount%>
                </i>
                <% End If%>        
                </center>
        </div>
    </div>
</div>
<div id="dialog" title="Message"><asp:Label runat="server" Text="" ID="LblShowMsg"></asp:Label></div>
</asp:Content>
