'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SalesOrder
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''HeaderValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''FindDocNoValiadationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindDocNoValiadationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''FindSysDocNoValiadationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindSysDocNoValiadationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''lblForCustomerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForCustomerCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CustomerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerCoderRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerCoderRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''AutoCompleteExtenderCustomerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtenderCustomerCode As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''lblForCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForCustomerName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''AutoCompleteExtenderCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtenderCustomerName As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''lblForPaymentTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForPaymentTerms As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PaymentTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentTerms As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PONo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForShipAddressID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForShipAddressID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipTo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ValidShipToRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidShipToRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForAddressLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAddressLine1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddressLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressLine1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForAddressLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAddressLine2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddressLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressLine2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForAddressLine3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAddressLine3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddressLine3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressLine3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForAddressLine4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAddressLine4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddressLine4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressLine4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForAddressLine5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAddressLine5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddressLine5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressLine5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFindDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindDocNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtFindDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindDocNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FindDocNoRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindDocNoRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''FindDONoAutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindDONoAutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''btnFindSAPDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindSAPDocNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtFindSAPDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindSAPDocNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FindSAPDocNoRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindSAPDocNoRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''FindSAPDocNoAutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindSAPDocNoAutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''lblForIdKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForIdKey As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SONo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblForSAPSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForSAPSONo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SAPSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SAPSONo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblForStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblForDocDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForDocDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DocDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DocDateRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocDateRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''DocDateCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocDateCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblForDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForDeliveryDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeliveryDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DeliveryDateRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeliveryDateRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''DeliveryDateCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeliveryDateCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''ValidationSummaryItemsAddValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryItemsAddValidation As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''ValidationSummaryItemsUpdateValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryItemsUpdateValidation As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''SalesOrderLinesGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SalesOrderLinesGrid As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Remarks As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblForSubTotalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForSubTotalAmt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SubTotalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubTotalAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidSubTotalAmtRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidSubTotalAmtRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForOrderDiscPrsnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForOrderDiscPrsnt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OrderDiscPrsnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscPrsnt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidOrderDiscPrsntRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidOrderDiscPrsntRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForOrderDiscAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForOrderDiscAmt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OrderDiscAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidOrderDiscAmtRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidOrderDiscAmtRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForAmtAfterDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAmtAfterDiscount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AmtAfterDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmtAfterDiscount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidAmtAfterDiscountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidAmtAfterDiscountRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForGSTPrsnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForGSTPrsnt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GSTPrsnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GSTPrsnt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidGSTPrsntRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidGSTPrsntRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForGSTAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GSTAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidGSTAmountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidGSTAmountRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblForTotalInvAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForTotalInvAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TotalSOAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalSOAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ValidTotalInvAmountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidTotalInvAmountRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSubmitToSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitToSAP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreview As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblShowMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblShowMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblConfirmMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNotConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNotConfirm As Global.System.Web.UI.WebControls.Button
End Class
