<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="ManageRoles.aspx.vb" Inherits="SchloetterSalesPortal.ManageRoles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <h2>Manage Roles</h2>
   <div class="MainContent">
                    <div class="FormHeader">  
                  
<div id="content">
<div id="left" style="float:left;width:40%;border:1px; padding-right: 20px;">
<asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="Group1" runat="server" HeaderText="" ShowMessageBox="false" DisplayMode="BulletList" ShowSummary="true"  ForeColor="Red" Font-Size="Medium" /><asp:Label ID="lblMsg" runat="server" Text=""  Visible="false"></asp:Label>
<div >
                        <fieldset class="register">
                         <legend>Add User Roles</legend>
                         <p>
                         <asp:Label ID="Label1" runat="server" AssociatedControlID="txtRoleName">Role Name:</asp:Label>
                         <asp:TextBox ID="txtRoleName" runat="server"  CssClass="textEntry"  MaxLength="50"></asp:TextBox>
                  <asp:RequiredFieldValidator Display="Dynamic" ID="RequiredFieldValidator2" runat="server"  ControlToValidate="txtRoleName"
                          ErrorMessage="Role Name Required" SetFocusOnError="true" Text="*" ValidationGroup="Group1"></asp:RequiredFieldValidator>
                          <asp:RegularExpressionValidator
                              ID="RegularExpressionValidator2" runat="server" Display="Dynamic" ErrorMessage="Invalid RoleName" Text="*" ControlToValidate="txtRoleName" ValidationExpression="^[a-zA-Z-'.\s]{1,50}$" ValidationGroup="Group1"></asp:RegularExpressionValidator>
                      <asp:CustomValidator ID="CustomValidator2" runat="server" 
                          ErrorMessage="Aleary Exist" Text="*"   Display="Dynamic" ControlToValidate="txtRoleName" OnServerValidate="CheckExist" ValidationGroup="Group1"  ></asp:CustomValidator>
                         </p>
                         <p class="submitButton">
                            <asp:Button ID="btnSubmit" runat="server" Text="Submit"  ValidationGroup="Group1"  />
                         </p>
                         </fieldset>
</div>
</div>
<div id="right" style="float:right;width:55%;border:1px;">
<div >
                        <fieldset class="register">
                         <legend>List of Roles</legend>
 <asp:GridView ID="RolesGrid" runat="server" CellPadding="4" ForeColor="#333333"  Width="50%"
                    GridLines="None" AutoGenerateColumns="false" AutoGenerateDeleteButton="True"   onrowdeleting="RolesGrid_RowDeleting">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                      <Columns>
                  <asp:TemplateField HeaderText="List of available roles" >
                      <ItemTemplate >                       
                          <asp:Label ID="lblRoleName" runat="server" Text="  <%# Container.DataItem.ToString() %>"></asp:Label>
                      </ItemTemplate>
                  </asp:TemplateField>
              </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
                </fieldset>
                </div>
</div>
</div>
  </div>
                    </div>
                    <div id="dialog" title="Message"><asp:Label runat="server" Text="" ID="LblShowMsg"></asp:Label></div>   
</asp:Content>


